2020-09-20 16:35:04,887 ERROR: Exception on / [GET] [in c:\users\andoreazu\documents\eksplore\python\flask\virtualenv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "c:\users\andoreazu\documents\eksplore\python\flask\virtualenv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\andoreazu\documents\eksplore\python\flask\virtualenv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\andoreazu\documents\eksplore\python\flask\virtualenv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\andoreazu\documents\eksplore\python\flask\virtualenv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\andoreazu\documents\eksplore\python\flask\virtualenv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\andoreazu\documents\eksplore\python\flask\virtualenv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\andoreazu\documents\eksplore\python\flask\virtualenv\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\AndoreAZU\Documents\Eksplore\Python\Flask\app\routes.py", line 45, in index
    return render_template('index.html', title='Home', form=form,
  File "c:\users\andoreazu\documents\eksplore\python\flask\virtualenv\lib\site-packages\flask\templating.py", line 137, in render_template
    return _render(
  File "c:\users\andoreazu\documents\eksplore\python\flask\virtualenv\lib\site-packages\flask\templating.py", line 120, in _render
    rv = template.render(context)
  File "c:\users\andoreazu\documents\eksplore\python\flask\virtualenv\lib\site-packages\jinja2\environment.py", line 1090, in render
    self.environment.handle_exception()
  File "c:\users\andoreazu\documents\eksplore\python\flask\virtualenv\lib\site-packages\jinja2\environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "c:\users\andoreazu\documents\eksplore\python\flask\virtualenv\lib\site-packages\jinja2\_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\AndoreAZU\Documents\Eksplore\Python\Flask\app\templates\index.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "C:\Users\AndoreAZU\Documents\Eksplore\Python\Flask\app\templates\base.html", line 1, in top-level template code
    {% extends 'bootstrap/base.html' %}
  File "c:\users\andoreazu\documents\eksplore\python\flask\virtualenv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 1, in top-level template code
    {% block doc -%}
  File "c:\users\andoreazu\documents\eksplore\python\flask\virtualenv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 4, in block "doc"
    {%- block html %}
  File "c:\users\andoreazu\documents\eksplore\python\flask\virtualenv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 20, in block "html"
    {% block body -%}
  File "c:\users\andoreazu\documents\eksplore\python\flask\virtualenv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 21, in block "body"
    {% block navbar %}
  File "C:\Users\AndoreAZU\Documents\Eksplore\Python\Flask\app\templates\base.html", line 21, in block "navbar"
    <li><a href="{{ url_for('index') }}">{{ _('Home') }}</a></li>
jinja2.exceptions.UndefinedError: '_' is undefined
2020-09-20 16:35:38,722 INFO: Microblog startup [in C:\Users\AndoreAZU\Documents\Eksplore\Python\Flask\app\__init__.py:47]
2020-09-20 16:43:43,637 INFO: Microblog startup [in C:\Users\AndoreAZU\Documents\Eksplore\Python\Flask\app\__init__.py:47]
2020-09-20 16:46:13,676 INFO: Microblog startup [in C:\Users\AndoreAZU\Documents\Eksplore\Python\Flask\app\__init__.py:47]
2020-09-21 09:56:58,395 INFO: Microblog startup [in C:\Users\AndoreAZU\Documents\Eksplore\Python\Flask\app\__init__.py:49]
